# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\craig\Documents\GitHub\CraigMEPTools\file_renamer_window_shadow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(1246, 932)
        Form.setToolTip("")
        Form.setStatusTip("")
        Form.setWhatsThis("")
        Form.setAccessibleName("")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.listWidget_column_2 = QtWidgets.QListWidget(Form)
        self.listWidget_column_2.setToolTip("")
        self.listWidget_column_2.setStatusTip("")
        self.listWidget_column_2.setWhatsThis("")
        self.listWidget_column_2.setAccessibleName("")
        self.listWidget_column_2.setObjectName("listWidget_column_2")
        self.gridLayout.addWidget(self.listWidget_column_2, 1, 2, 1, 1)
        self.listWidget_column_1 = QtWidgets.QListWidget(Form)
        self.listWidget_column_1.setObjectName("listWidget_column_1")
        self.gridLayout.addWidget(self.listWidget_column_1, 1, 1, 1, 1)
        self.introduction_label = QtWidgets.QLabel(Form)
        self.introduction_label.setObjectName("introduction_label")
        self.gridLayout.addWidget(self.introduction_label, 0, 0, 1, 1)
        self.column_2_label = QtWidgets.QLabel(Form)
        self.column_2_label.setObjectName("column_2_label")
        self.gridLayout.addWidget(self.column_2_label, 0, 2, 1, 1)
        self.column_1_label = QtWidgets.QLabel(Form)
        self.column_1_label.setObjectName("column_1_label")
        self.gridLayout.addWidget(self.column_1_label, 0, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.step_1_label = QtWidgets.QLabel(Form)
        self.step_1_label.setObjectName("step_1_label")
        self.gridLayout_2.addWidget(self.step_1_label, 0, 0, 1, 1)
        self.step_3_label = QtWidgets.QLabel(Form)
        self.step_3_label.setObjectName("step_3_label")
        self.gridLayout_2.addWidget(self.step_3_label, 2, 0, 1, 1)
        self.step_2_label = QtWidgets.QLabel(Form)
        self.step_2_label.setObjectName("step_2_label")
        self.gridLayout_2.addWidget(self.step_2_label, 1, 0, 1, 1)
        self.step_4_label = QtWidgets.QLabel(Form)
        self.step_4_label.setObjectName("step_4_label")
        self.gridLayout_2.addWidget(self.step_4_label, 3, 0, 1, 1)
        self.button_1_label = QtWidgets.QLabel(Form)
        self.button_1_label.setObjectName("button_1_label")
        self.gridLayout_2.addWidget(self.button_1_label, 0, 1, 1, 1)
        self.step_5_label = QtWidgets.QLabel(Form)
        self.step_5_label.setObjectName("step_5_label")
        self.gridLayout_2.addWidget(self.step_5_label, 4, 0, 1, 1)
        self.button_2_label = QtWidgets.QLabel(Form)
        self.button_2_label.setObjectName("button_2_label")
        self.gridLayout_2.addWidget(self.button_2_label, 1, 1, 1, 1)
        self.button_4_label = QtWidgets.QLabel(Form)
        self.button_4_label.setObjectName("button_4_label")
        self.gridLayout_2.addWidget(self.button_4_label, 3, 1, 1, 1)
        self.button_5_label = QtWidgets.QLabel(Form)
        self.button_5_label.setObjectName("button_5_label")
        self.gridLayout_2.addWidget(self.button_5_label, 4, 1, 1, 1)
        self.button_3_label = QtWidgets.QLabel(Form)
        self.button_3_label.setObjectName("button_3_label")
        self.gridLayout_2.addWidget(self.button_3_label, 2, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.author_info_label = QtWidgets.QLabel(Form)
        self.author_info_label.setObjectName("author_info_label")
        self.gridLayout.addWidget(self.author_info_label, 2, 2, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.introduction_label.setText(_translate("Form", "Introduction to the section."))
        self.column_2_label.setText(_translate("Form", "Column 2 Title"))
        self.column_1_label.setText(_translate("Form", "Column 1 Title"))
        self.step_1_label.setText(_translate("Form", "Step 1"))
        self.step_3_label.setText(_translate("Form", "Step 3"))
        self.step_2_label.setText(_translate("Form", "Step 2"))
        self.step_4_label.setText(_translate("Form", "Step 4"))
        self.button_1_label.setText(_translate("Form", "Button 1"))
        self.step_5_label.setText(_translate("Form", "Step 5"))
        self.button_2_label.setText(_translate("Form", "Button 2"))
        self.button_4_label.setText(_translate("Form", "Button 4"))
        self.button_5_label.setText(_translate("Form", "Button 5"))
        self.button_3_label.setText(_translate("Form", "Button 3"))
        self.author_info_label.setText(_translate("Form", "Author info"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

